/**
 * Export helpers. Everything here genuinely works client-side today:
 * storyboard markdown and caption text are plain strings, and carousel slides
 * are drawn onto a canvas and downloaded as real PNG files. Nothing in this
 * module pretends to render MP4s or narration.
 */
import type { ContentPack } from "@/contracts";

export function buildCaptionText(pack: ContentPack): string {
  const hashtags = pack.hashtags.join(" ");
  return hashtags.length > 0 ? `${pack.caption}\n\n${hashtags}` : pack.caption;
}

export function buildStoryboardMarkdown(pack: ContentPack): string {
  const totalSeconds = pack.scenes.reduce(
    (sum, scene) => sum + scene.durationSeconds,
    0,
  );
  const isShort = pack.format === "short";

  const lines: string[] = [
    `# ${pack.title}`,
    "",
    `> ${isShort ? "YouTube Short storyboard" : "Carousel storyboard"} — generated by NextBestContent by Tripods`,
    "",
    `**Hook:** ${pack.hook}`,
    "",
    `**Angle:** ${pack.angle}`,
    "",
    isShort ? `**Runtime:** ${Math.round(totalSeconds)}s across 6 scenes` : "**Structure:** 6 reader-paced slides",
    "",
    "---",
    "",
  ];

  for (const scene of pack.scenes) {
    lines.push(
      `## ${isShort ? "Scene" : "Slide"} ${scene.index + 1}${isShort ? ` · ${scene.durationSeconds}s` : ""}`,
      "",
      `**On-screen headline:** ${scene.headline}`,
      "",
      `**On-screen body:** ${scene.body}`,
      "",
      `**Visual direction:** ${scene.visualDirection}`,
      "",
    );
    if (isShort) {
      lines.push(`**Voiceover:** ${scene.voiceover}`, "");
    }
  }

  lines.push(
    "---",
    "",
    `**Caption:** ${pack.caption}`,
    "",
    `**Call to action:** ${pack.cta}`,
    "",
    `**Hashtags:** ${pack.hashtags.join(" ")}`,
    "",
    `**Backed by:** ${pack.sourceEvidence.length} audience comments behind the signal "${pack.sourceSignal.title}"`,
    "",
    `**Provenance:** ${pack.provenance.source === "demo" ? "Synthetic demo data (fictional fixture)" : pack.provenance.source}`,
    "",
  );

  return lines.join("\n");
}

export function downloadTextFile(
  filename: string,
  contents: string,
  mimeType = "text/markdown",
): void {
  const blob = new Blob([contents], { type: `${mimeType};charset=utf-8` });
  triggerDownload(URL.createObjectURL(blob), filename, true);
}

function triggerDownload(href: string, filename: string, revoke: boolean) {
  const anchor = document.createElement("a");
  anchor.href = href;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  if (revoke) {
    setTimeout(() => URL.revokeObjectURL(href), 1_000);
  }
}

const SLIDE_WIDTH = 1080;
const SLIDE_HEIGHT = 1350;

function wrapLines(
  context: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current.length > 0 ? `${current} ${word}` : word;
    if (context.measureText(candidate).width <= maxWidth || current === "") {
      current = candidate;
    } else {
      lines.push(current);
      current = word;
    }
  }
  if (current.length > 0) {
    lines.push(current);
  }
  return lines;
}

function drawWrapped(
  context: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  let cursor = y;
  for (const line of wrapLines(context, text, maxWidth)) {
    context.fillText(line, x, cursor);
    cursor += lineHeight;
  }
  return cursor;
}

/**
 * Draws one carousel slide (1080×1350) onto a canvas and resolves with a PNG
 * blob. Pure canvas drawing — no external assets, so the canvas never taints.
 */
export function renderSlideImage(
  pack: ContentPack,
  sceneIndex: number,
): Promise<Blob> {
  const scene = pack.scenes[sceneIndex];
  if (!scene) {
    return Promise.reject(new Error(`No scene at index ${sceneIndex}`));
  }

  const canvas = document.createElement("canvas");
  canvas.width = SLIDE_WIDTH;
  canvas.height = SLIDE_HEIGHT;
  const context = canvas.getContext("2d");
  if (!context) {
    return Promise.reject(new Error("Canvas 2D is unavailable"));
  }

  // Background
  context.fillStyle = "#12130f";
  context.fillRect(0, 0, SLIDE_WIDTH, SLIDE_HEIGHT);

  // Accent rule
  context.fillStyle = "#c9f24f";
  context.fillRect(96, 128, 88, 10);

  // Slide counter
  context.fillStyle = "#8f9288";
  context.font = "600 34px Arial, sans-serif";
  context.textBaseline = "top";
  context.fillText(
    `${scene.index + 1} / ${pack.scenes.length}`,
    SLIDE_WIDTH - 96 - context.measureText(`${scene.index + 1} / ${pack.scenes.length}`).width,
    118,
  );

  // Headline
  context.fillStyle = "#f4f3ee";
  context.font = "700 84px Georgia, 'Times New Roman', serif";
  const afterHeadline = drawWrapped(
    context,
    scene.headline,
    96,
    208,
    SLIDE_WIDTH - 192,
    98,
  );

  // Body
  context.fillStyle = "#c9cbc2";
  context.font = "400 46px Arial, sans-serif";
  drawWrapped(context, scene.body, 96, afterHeadline + 48, SLIDE_WIDTH - 192, 66);

  // Footer
  context.fillStyle = "#8f9288";
  context.font = "600 32px Arial, sans-serif";
  context.fillText("NextBestContent · by Tripods", 96, SLIDE_HEIGHT - 150);
  if (pack.provenance.source === "demo") {
    context.fillStyle = "#c9f24f";
    context.fillText("Synthetic demo content", 96, SLIDE_HEIGHT - 100);
  }

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) {
        resolve(blob);
      } else {
        reject(new Error("Canvas export failed"));
      }
    }, "image/png");
  });
}

export async function downloadSlideImage(
  pack: ContentPack,
  sceneIndex: number,
): Promise<void> {
  const blob = await renderSlideImage(pack, sceneIndex);
  triggerDownload(
    URL.createObjectURL(blob),
    `nextbestcontent-slide-${sceneIndex + 1}.png`,
    true,
  );
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
